Remove doc reference to "import -t" (for now)
It is currently broke due to 'set -u' and on testing, I can't seem
to get it working properly based on the docs/help:

$ sudo singularity import -t docker ubuntu /tmp/Moo.img
ERROR: No Docker image specified (with --file)

So to work around the problem and not delay the release, I am hiding
the feature so we can still debug and fix, but not delay release on
a broken feature.