py2/py3 compatibility for urllib
Documentation at http://singularity.lbl.gov/docs-exec shows running this example
$ singularity exec docker://python:latest /usr/local/bin/python hello.py
Doing so with python3 as default python interpreter brings up an error as urllib2 is python2 only:
ImportError: No module named 'urllib2'
This is a change to make the code py2/py3 compatible